{% set goname = "github.com/go-task/task" %}
{% set name = "go-task" %}
{% set version = "3.31.0" %}

{% set pkg_src = ('src/'+goname).replace("/",os.sep) %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  - folder: {{ pkg_src }}
    url: https://{{ goname }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 189f3b98ed6b15290d4fd4dbab687c87de268b5c9f2f1c93a7c02710da062785

build:
  number: 1
  script:
    - pushd {{ pkg_src }}
    - go install -v -ldflags="-w -s -X main.version=conda-forge" ./cmd/task  # [win]
    - go build -v -ldflags="-w -s -X main.version=conda-forge" -o $PREFIX/bin/task ./cmd/task  # [not win]
    - go-licenses save "." --save_path "library_licenses"

requirements:
  build:
    - {{ compiler('go') }}
    - go-nocgo
    - go-licenses

test:
  commands:
    - task --version

about:
  home: https://taskfile.dev/
  summary: A task runner / simpler Make alternative written in Go.
  description: |
    Task is a task runner / build tool that aims to be simpler and easier
    to use than, for example, GNU Make. 
  license: MIT
  license_family: MIT
  license_file:
    - {{ pkg_src }}/LICENSE
    - {{ pkg_src }}/library_licenses/
  doc_url: https://taskfile.dev/
  dev_url: https://github.com/go-task/task

extra:
  recipe-maintainers:
    - AntoinePrv
