context:
  goname: github.com/go-task/task
  name: go-task
  version: 3.43.2
  pkg_src: ${{ ["src", goname] | join("/") }}

package:
  name: ${{ name | lower }}
  version: ${{ version | replace("-", "_") }}

source:
  - target_directory: ${{ pkg_src }}
    url: https://${{ goname }}/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 41ed911af61d582e2824e2ee6ac8b1a845968b09ed188e79846557226aa96bed

build:
  number: 0
  script:
    - pushd '${{ pkg_src }}'
    - if: win
      then: go install -v -ldflags="-w -s -X main.version=conda-forge" ./cmd/task
      else: go build -v -ldflags="-w -s -X main.version=conda-forge" -o $PREFIX/bin/task ./cmd/task
    - go-licenses save "." --save_path "library_licenses" --ignore github.com/go-task/template

requirements:
  build:
    - ${{ compiler('go') }}
    - ${{ stdlib('c') }}
    - go-nocgo
    - go-licenses

tests:
  - script:
    - task --version

about:
  homepage: https://taskfile.dev/
  summary: A task runner / simpler Make alternative written in Go.
  description: |
    Task is a task runner / build tool that aims to be simpler and easier
    to use than, for example, GNU Make. 
  license: MIT
  license_family: MIT
  license_file:
    - ${{ pkg_src }}/LICENSE
    - ${{ pkg_src }}/library_licenses/
  documentation: https://taskfile.dev/
  repository: https://github.com/go-task/task

extra:
  recipe-maintainers:
    - AntoinePrv
