github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_build_tool: rattler-build
conda_install_tool: pixi
conda_forge_output_validation: true
bot:
  automerge: true
build_platform:
  linux_ppc64le: linux_64
  linux_aarch64: linux_64
  osx_arm64: osx_64
test: native_and_emulated
