github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
bot:
  automerge: true
provider: { linux_aarch64: default, linux_ppc64le: azure }
build_platform:
  osx_arm64: osx_64
test: native_and_emulated
